# Header
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag

# favicon
favicon: /favicon.ico

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/Aceris-9527
  #ZhiHu:
  #Twitter:
  #Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo: Aceris-9527/blog
  repo_id: R_kgDOSCTXeg
  category: Announcements
  category_id: DIC_kwDOSCTXes4C60wn
  mapping: pathname

# maple
maple:
  enable: true
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5
